function [fitresult, gof] = FitEC_Gaussian7(fileName)
%CREATEFIT(X2,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X2
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jul-2017 17:32:07


origData = dlmread( fileName );
X = origData( 522:850, 1 );
Y = origData( 522:850, 2 );

baseLine = polyfit([X(1),X(329)],[Y(1),Y(329)],1);
Y = Y - polyval(baseLine, X);

[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'gauss7' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 690 7 0 -Inf 0 0 500 0 0 -Inf 0 -Inf -Inf 0 50 640 0 -Inf 560 0];
opts.StartPoint = [938 704 6 636 653 7 100 510 8 555 713 10 455 638 10 150 650 12 329 581 14];
opts.Upper = [Inf 715 30 Inf Inf Inf Inf 530 20 100 730 70 170 670 70 200 680 Inf Inf 600 20];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



plotGaussian8(X, Y, fitresult, 7);
figTitle = strrep(fileName, '_', ',');
title(figTitle);