function [fitresult, gof] = FitEC_Gaussian5(fileName)
%CREATEFIT(X2,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X2
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jul-2017 17:32:07


origData = dlmread( fileName );
X = origData( 582:910, 1 );
Y = origData( 582:910, 2 );

baseLine = polyfit([X(1),X(329)],[Y(1),Y(329)],1);
Y = Y - polyval(baseLine, X);

[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'gauss5' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 600 20 500 550 20 0 370 20 0 640 20 0 500 20];
opts.MaxFunEvals = 1000;
opts.MaxIter = 2000;
opts.StartPoint = [431 622 42 650 574 15 37 400 18 388 682 66 488 527 99];
opts.Upper = [1000 660 50 800 590 30 500 420 70 300 700 80 700 550 80];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

plotGaussian8(X, Y, fitresult, 5);
figTitle = strrep(fileName, '_', ',');
title(figTitle);


