function [fitresult, X] = FitEC_Gaussian8( fileName )
%CREATEFIT(X2,Y2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X2
%      Y Output: Y2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jul-2017 15:20:30


%% Fit: 'untitled fit 1'.

origData = dlmread( fileName );
X = origData( 582:910, 1 );
Y = origData( 582:910, 2 );

baseLine = polyfit([X(1),X(329)],[Y(1),Y(329)],1);
Y = Y - polyval(baseLine, X);

[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 600 15 0 620 15 0 565 15 0 490 15 0 460 15 0 400 15 0 400 15 0 600 15];
opts.MaxFunEvals = 1000;
opts.MaxIter = 2000;
opts.StartPoint = [100 610 20 800 635 40 800 581.556 30 810.2779 514 30 377.7769 480.585 23.6011 300 420 30 100 450 50 50 620 50];
opts.Upper = [100 620 40 2000 655 80 2000 600 120 2000 540 150 2000 500 120 2000 450 100 500 450 150 100 635 35];


% Fit model to data.
fitresult = fit( xData, yData, ft, opts );


plotGaussian8(X, Y, fitresult, 8);
figTitle = strrep(fileName, '_', ',');
title(figTitle);



