function returnmatrix = importavantesfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 21-Jun-2016 11:55:10

% Import the file
newData1 = importdata(fileToRead1);
returnmatrix = newData1.('data')(:,1:2);

