function DeFLY = partialRMFL(DataX, DataY, baselinecount)
%CREATEFIT(INCELLHEX,INCELLHEY)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : InCellHeX
%      Y Output: InCellHeY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jun-2016 15:46:46


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( [(DataX(50:baselinecount))',(DataX(1400:1771))']', [(DataY(50:baselinecount))',(DataY(1400:1771))']' );

% Set up fittype and options.
ft = fittype( 'poly4' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf];
opts.Robust = 'Bisquare';
opts.Upper = [Inf Inf Inf Inf Inf];
%.Normalize = 'on'; %bizarre things happens when switched on.

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

DeFLY = DataY - polyval(coeffvalues(fitresult), DataX);

% Plot fit with data.
%figure( 'Name', 'untitled fit 2' );
%h = plot( fitresult, xData, yData );
%legend( h, 'InCellHeY vs. InCellHeX', 'untitled fit 2', 'Location', 'NorthEast' );
% Label axes
%xlabel( 'InCellHeX' );
%ylabel( 'InCellHeY' );
%grid on


